package com.cocosh.shmstore.model

import com.google.gson.Gson


/**
 * 用户实体类
 * Created by lmg on 2017/1/4.
 */

class UserModel {
    var CJf = "0"
    var back_ground = ""
    var caddress = ""
    var cage = ""
    var carea = ""
    var cavatar = ""
    var cbirthday = ""
    var ccity = ""
    var ccname = ""
    var cda = ""
    var cfaren = ""
    var cfax = ""
    var cid = ""
    var cinvite = ""
    var cip = ""
    var city_id = ""
    var clicense = ""
    var clogdate = ""
    var cmail = ""
    var cmob = ""
    var cmoney = ""
    var cmtype = ""
    var cnick = ""
    var company_title = ""
    var cpass = ""
    var cpassOne = ""
    var cpassTwo = ""
    var cpname = ""
    var cprovince = ""
    var cqq = ""
    var cquan = ""
    var cregdate = ""
    var csex = ""
    var ctel = ""
    var ctname = ""
    var cuserid = ""
    var cwt = ""
    var czip = ""
    var deviceid = ""
    var devicetype = ""
    var dynamic_image = ""
    var entrepreneurBalance = ""
    var entrepreneur_id = ""
    var entrepreneur_idcard_id = ""
    var frozen_money = ""
    var idcard_id = ""
    var invite_code = ""
    var is_Area = ""
    var is_Interest = ""
    var is_login = ""
    var is_take = ""
    var latitude = ""
    var longitude = ""
    var media_token = ""
    var member_level = ""
    var newCpass = ""
    var newCpassOne = ""
    var openid = ""
    var operator_idcard_id = ""
    var partnerBalance = ""
    var partner_code = ""
    var partner_id = ""
    var pay_pwd = ""
    var profession_title = ""
    var qq_name = ""
    var qq_openid = ""
    var receive_qrcode = ""
    var redBalance = ""
    var redIdcardStatus = ""
    var red_idcard_id = ""
    var referee_uid = ""
    var sina_openid = ""
    var sm_code_disable = ""
    var smcode = ""
    var source = ""
    var status = ""
    var tcard = ""
    var thirdToken = ""
    var thirdType = ""
    var token = ""
    var verify_city_operators = ""
    var verify_entrepreneur = ""
    var verify_idcard = ""
    var verify_media = ""
    var verify_mobile = ""
    var verify_partner = ""
    var wb_name = ""
    var wx_name = ""

    override fun toString(): String =
            "UserModel(CJf='$CJf', back_ground='$back_ground', caddress='$caddress', cage='$cage', carea='$carea', cavatar='$cavatar', cbirthday='$cbirthday', ccity='$ccity', ccname='$ccname', cda='$cda', cfaren='$cfaren', cfax='$cfax', cid='$cid', cinvite='$cinvite', cip='$cip', city_id='$city_id', clicense='$clicense', clogdate='$clogdate', cmail='$cmail', cmob='$cmob', cmoney='$cmoney', cmtype='$cmtype', cnick='$cnick', company_title='$company_title', cpass='$cpass', cpassOne='$cpassOne', cpassTwo='$cpassTwo', cpname='$cpname', cprovince='$cprovince', cqq='$cqq', cquan='$cquan', cregdate='$cregdate', csex='$csex', ctel='$ctel', ctname='$ctname', cuserid='$cuserid', cwt='$cwt', czip='$czip', deviceid='$deviceid', devicetype='$devicetype', dynamic_image='$dynamic_image', entrepreneurBalance='$entrepreneurBalance', entrepreneur_id='$entrepreneur_id', entrepreneur_idcard_id='$entrepreneur_idcard_id', frozen_money='$frozen_money', idcard_id='$idcard_id', invite_code='$invite_code', is_Area='$is_Area', is_Interest='$is_Interest', is_login='$is_login', is_take='$is_take', latitude='$latitude', longitude='$longitude', media_token='$media_token', member_level='$member_level', newCpass='$newCpass', newCpassOne='$newCpassOne', openid='$openid', operator_idcard_id='$operator_idcard_id', partnerBalance='$partnerBalance', partner_code='$partner_code', partner_id='$partner_id', pay_pwd='$pay_pwd', profession_title='$profession_title', qq_name='$qq_name', qq_openid='$qq_openid', receive_qrcode='$receive_qrcode', redBalance='$redBalance', redIdcardStatus='$redIdcardStatus', red_idcard_id='$red_idcard_id', referee_uid='$referee_uid', sina_openid='$sina_openid', sm_code_disable='$sm_code_disable', smcode='$smcode', source='$source', status='$status', tcard='$tcard', thirdToken='$thirdToken', thirdType='$thirdType', token='$token', verify_city_operators='$verify_city_operators', verify_entrepreneur='$verify_entrepreneur', verify_idcard='$verify_idcard', verify_media='$verify_media', verify_mobile='$verify_mobile', verify_partner='$verify_partner', wb_name='$wb_name', wx_name='$wx_name')"


    fun toJson(): String = Gson().toJson(this)

}
